// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9mV-BoCBats2GDMZjcvjAloxgLQtJOv8',
    appId: '1:1013219673970:web:7da7cd7f0b6da814e13feb',
    messagingSenderId: '1013219673970',
    projectId: 'visit-vault',
    authDomain: 'visit-vault.firebaseapp.com',
    storageBucket: 'visit-vault.appspot.com',
    measurementId: 'G-G6X3GYP1TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLxaHMc0w26DpGMpC0CgOPUqr-RYyVnQ',
    appId: '1:1013219673970:android:dde873a886b9f867e13feb',
    messagingSenderId: '1013219673970',
    projectId: 'visit-vault',
    storageBucket: 'visit-vault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2K6nQBMmTo11hl2emdY4wPOJKsHE2UF0',
    appId: '1:1013219673970:ios:6020efc078de3482e13feb',
    messagingSenderId: '1013219673970',
    projectId: 'visit-vault',
    storageBucket: 'visit-vault.appspot.com',
    iosBundleId: 'com.example.visitVault',
  );
}
